version: '4'

services:

    nginx:
        image: nginx:latest
        volumes:
          - ./:/var/www
          - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8080:80"
        container_name: nginx_lara
        depends_on:
          - app
          -
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
          - ./:/var/www
        depends_on:
            - db
        container_name: project_lara

    db:
        image: postgres:16
        restart: always
        volumes:
            - ./tmp/pgsql:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_HOST_AUTH_METHOD="trust"
        ports:
            - "5433:5432"
        container_name: project_db

    npm:
        image: node:lts
        volumes:
            - ./src:/var/www/html
        ports:
            - "3000:3000"
        entrypoint: ["npm", "run", "dev"]
        working_dir: /var/www/html
        container_name: project_node

    artisan:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./src:/var/www/html
        depends_on:
            - db
        container_name: artisan
        entrypoint: [ '/var/www/html/artisan' ]
        working_dir: /var/www/html





